# KeyError --> It happens when we try to access the key which is not present in the dict

my_dict = {"name": "ankita"}
# my_dict["age"]  --> KeyError
print(my_dict)