# ValueError - It happens when the function or operation receives an argument that has a right type
# but an inappropriate value

a = [1,2,3,4]
a.remove(1)
print(a)


# ValueError - Because 5 is not in the list
# a.remove(5)
print(a)